networks:
  app_network:
    driver: bridge

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/var/www/html
      - ./.docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www/html
    restart: always
    depends_on:
      - nginx
      - postgres
    networks:
      - app_network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always
    networks:
      - app_network

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: proprli
      POSTGRES_USER: proprli
      POSTGRES_PASSWORD: proprli
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

volumes:
  postgres_data:
